### ISSUE TITLE
Improperly displaying data and errors when modifying

### ISSUE THREAD

**Issue by apappu9** [MinhyukPark/DataspreadFrontend#6]
![image](https://user-images.githubusercontent.com/22779056/71706244-519a2180-2da9-11ea-8a33-334905fd23be.png)

Contents of SQL table:
![image](https://user-images.githubusercontent.com/22779056/71706268-768e9480-2da9-11ea-987b-64065cb82488.png)

**Comment by MinhyukPark** [comment]
Ah. Ok i see what's happening. The first thing you should do here is deleting the .dat files in your backend directory. After that the errors you're seeing might go away. Also delete the .csv file.

**Comment by MinhyukPark** [comment]
Make sure you're running the newest version by pulling from origin again as well

**Comment by apappu9** [comment]
Thanks, that seemed to have fixed the issue. Everything works as expected now
